
server:
  port: 8080
    

spring:
  profiles:
    active: h2
#    active: maria
    
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    
  datasource:
#    driver-class-name : org.mariadb.jdbc.Driver
#    url               : jdbc:mariadb://10.0.0.2:3306/boardpt
#    username          : root
#    password          : root
    
#    driver-class-name : org.h2.Driver
#    url               : jdbc:h2:C:/workspace/boardpt
#    username          : sa
#    password          : 
    hikari:
#      driver-class-name: org.mariadb.jdbc.Driver
#      jdbc-url: jdbc:mariadb://10.0.0.2:3306/boardpt
#      username: root
#      password: root
#      driver-class-name: org.h2.Driver
#      jdbc-url: jdbc:h2:tcp://localhost/~/../../workspace/boardpt
#      username: sa
#      password: 
      maximum-pool-size : 30
      pool-name         : BoardCP
#      minimum-idle: 5
      
  
#  h2:
#    console:
#      enabled: false
#      path    : /h2-console
#      settings:
#        web-allow-others: true

  servlet:
    multipart:
      enabled       : true
      location      : download
      max-file-size : 100MB
       
      
      
    
mybatis:
  type-aliases-package: com.board.dto
  mapper-locations    : static/mapper/*.xml
  
logging:
  file:
    path        : logging
#    max-size    : 100MB
#    max-history : 1
#    
#  pattern:
#    console: "%-5level %d{HH:mm:ss.SSS} [%-40.40logger] %-3L / %-15.15M : %m%n"
#    file: "LogFile_%d{yyyy-MM-dd}.log"
  
  
file:
  path: download
  
---

spring:
  profiles: h2
  
  datasource:
    driver-class-name : org.h2.Driver
    url               : jdbc:h2:C:/workspace/boardpt
    username          : sa
    password          : 

  
---

spring:
  profiles: maria

  datasource:
    driver-class-name : org.mariadb.jdbc.Driver
    url               : jdbc:mariadb://10.0.0.2:3306/boardpt
    username          : root
    password          : root
    
   


      
      